/**
 * Activity type icons - used across ActivityList, ActivityCard, ActivityDetail, etc.
 * Covers common Strava activity types.
 */
export function getActivityIcon(type: string): string {
  const icons: Record<string, string> = {
    Run: '🏃',
    Ride: '🚴',
    VirtualRide: '🖥️',
    VirtualRun: '🖥️',
    Walk: '🚶',
    Hike: '🥾',
    Swim: '🏊',
    Workout: '💪',
    Yoga: '🧘',
    WeightTraining: '🏋️',
    RockClimbing: '🧗',
    Crossfit: '💪',
    Elliptical: '🏃',
    Rowing: '🚣',
    Kayaking: '🛶',
    Canoeing: '🛶',
    StandUpPaddling: '🏄',
    Surfing: '🏄',
    Kitesurf: '🪁',
    Windsurf: '🏄',
    Snowboard: '🏂',
    AlpineSki: '⛷️',
    NordicSki: '⛷️',
    InlineSkate: '⛸️',
    Golf: '⛳',
    Tennis: '🎾',
    Badminton: '🏸',
    Pickleball: '🏓',
    Soccer: '⚽',
    Basketball: '🏀',
    Handball: '🤾',
    Rugby: '🏉',
    AmericanFootball: '🏈',
    Baseball: '⚾',
    Softball: '🥎',
    Volleyball: '🏐',
    Skateboard: '🛹',
    EBikeRide: '🔋',
    Velomobile: '🚴',
    Wheelchair: '♿',
    Snowshoe: '🥾',
    Sled: '🛷',
    IceSkate: '⛸️',
    Handcycle: '🚴',
    Unicycle: '🚴',
    StairStepper: '🪜',
    Pilates: '🧘',
    HIIT: '⚡',
    MartialArts: '🥋',
  };
  return icons[type] || '🏃';
}
